### ISSUE TITLE
build error: Missing executable permission on ./parse_zoneinfo.pl.

### ISSUE THREAD

**Issue by dreirund** [kevinboone/solunar_cmdline#4]
Executing `make` on checked-out git repository results in error

    make: execvp: ./parse_zoneinfo.pl: Permission denied

You need to set executable bit for that file.

Somewhen previously, it did build.

**Comment by vcrtech** [comment]
Make the parse_zoninfo.pl executable by doing "chmod +x parse_zoneinfo.pl" (without the quotes of course) in the same directory as the extracted files, then run make again.

**Comment by vcrtech** [comment]
Make the parse_zoneinfo.pl executable by doing "chmod +x parse_zoneinfo.pl" (without the quotes of course) in the same directory as the extracted files, then run make again.

**Comment by vcrtech** [comment]
Make the parse_zoneinfo.pl script executable by running "chmod +x parse_zoneinfo.pl" (without the quotes of course) in the same directory as the extracted files, then run make again.

**Comment by kevinboone** [comment]
It seems to be correct now. Please re-open if there is still a problem.
